name: bebusy

services:
  web:
    container_name: bebusy-nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./bebusy/_docker/services/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./bebusy:/app
    restart: always

  php:
    container_name: bebusy-php-fpm
    build:
      args:
        user: denchik
        uid: 1000
      context: ./bebusy/_docker/services/php
    ports:
      - "8083:8083"
      - "443:443"
    volumes:
      - ./bebusy:/app
      - ./bebusy/_docker/services/php/.bashrc:/home/denchik/.bashrc:ro
      - ./bebusy/_docker/services/php/laravel-reverb.conf:/etc/supervisor/conf.d/laravel-reverb.conf:ro
      - ./bebusy/_docker/services/php/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf:ro

  mysql:
    container_name: bebusy-mysql
    image: mysql
    restart: always
    volumes:
      - ./bebusy/_docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:3306"

  vite:
    container_name: bebusy-vite
    image: node:alpine
    entrypoint: /bin/sh
    ports:
      - "8082:8082"
    working_dir: /app
    tty: true
    volumes:
      - ./bebusy:/app
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
